# Generated by Django 6.0.6 on 2026-06-29 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('completed', 'Completed'), ('status_changed', 'Status changed'), ('logged_in', 'Logged in'), ('logged_out', 'Logged out'), ('registered', 'Registered'), ('profile_updated', 'Profile updated')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(default='fa-circle-info', help_text='Font Awesome icon class suffix, e.g. "fa-circle-check".', max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_activi_user_id_33cb61_idx')],
            },
        ),
    ]
